[build]
  base = "frontend"
  publish = ".next"
  command = "npm run build"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://zjrmogckkigdonifsfqg.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_Zl5aorSOQsYDGzZH4Q_1yg_4o8vqz6F"
  NEXT_PUBLIC_CARTO_API_KEY = "cb1_31yi_1_4a140fda7b4dd7d5fe46f34a"

[[plugins]]
  package = "@netlify/plugin-nextjs"

